--- 
changelog: 
  - 
    changes: 
      - 
        text: "channel and channels are the same argument."
        type: improvement
      - 
        text: "channel_group and channel_groups are the same argument."
        type: improvement
      - 
        text: "added `with_presence` flag for subscribe, default false."
        type: improvement
    date: ~
    version: v4.0.6
  - 
    changes: 
      - 
        text: "Required CGI."
        type: improvement
    version: v4.0.5
  - 
    changes: 
      - 
        text: Added
        type: feature
    version: v4.0.2
  - 
    changes: 
      - 
        text: "Updated dry-validation and EnvelopeSchema."
        type: improvement
    version: v4.0.1
  - 
    changes: 
      - 
        text: "Removed auth_key and uuid setters (#set_auth_key,"
        type: feature
      - 
        text: Added
        type: improvement
    version: v4.0.0
  - 
    changes: 
      - 
        text: "Restored auth_key and uuid setters. Important notice: they will be removed"
        type: improvement
    version: v3.8.3
  - 
    changes: 
      - 
        text: "Added :include_token parameter to history call."
        type: feature
    version: v3.8.2
  - 
    changes: 
      - 
        text: "Updated celluloid dependency."
        type: improvement
    version: v3.8.1
  - 
    changes: 
      - 
        text: "Release of celluloid version of pubnub gem. It's complete rewrite but public API doesn't change."
        type: improvement
    version: v3.8.0
features: 
  access: 
    - GRANT
    - AUDIT
  channel-groups: 
    - ADD-CHANNELS
    - REMOVE-CHANNELS
    - LIST-GROUPS
    - LIST-CHANNELS-IN-GROUP
  presence: 
    - HERE-NOW
    - WHERE-NOW
    - SET-STATE
    - GET-STATE
    - HEARTBEAT
  publish: 
    - STORE-FLAG
  push: 
    - ADD-DEVICE-TO-CHANNELS
    - REMOVE-DEVICE-FROM-CHANNELS
    - LIST-CHANNELS-FROM-DEVICE
    - REMOVE-DEVICE
name: ruby
schema: 1
scm: github.com/pubnub/ruby
version: "4.0.6"
