---
changelog:
  -
    changes:
      -
        text: "Fixed missing channel group parameter in leave event"
        type: bugfix
    date: ~
    version: v4.0.16
  -
    changes:
      -
        text: "Fixed PAM signature when some special characters are present"
        type: bugfix
    date: ~
    version: v4.0.15
  -
    changes:
      -
        text: "Added ttl parameter for publish"
        type: improvement
    date: ~
    version: v4.0.14
  -
    changes:
      -
        text: "Changed init message log level to debug"
        type: improvement
    date: ~
    version: v4.0.13
  -
    changes:
      -
        text: "Added alert on catchup failure (REQUEST_MESSAGE_COUNT_EXCEEDED)"
        type: improvement
    date: ~
    version: v4.0.12
  -
    changes:
      -
        text: "Added super admin mode (Enabled when secret key is set on Pubnub::Client init)"
        type: improvement
    date: ~
    version: v4.0.11
  -
    changes:
      -
        text: "Better single events timeout handling"
        type: improvement
      -
        text: "DRYed envelope formatting a bit"
        type: improvement
    date: ~
    version: v4.0.10
  -
    changes:
      -
        text: "Removed json dependency"
        type: improvement
      -
        text: "Updated dependecies"
        type: improvement
    date: ~
    version: v4.0.9
  -
    changes:
      -
        text: "Updated dry-validation."
        type: improvement
      -
        text: "Dropped support for ruby 2.0."
        type: improvement
    date: ~
    version: v4.0.8
  - 
    changes: 
      - 
        text: "Added message decrypting in history."
        type: improvement
    date: ~
    version: v4.0.7
  - 
    changes: 
      - 
        text: "channel and channels are the same argument."
        type: improvement
      - 
        text: "channel_group and channel_groups are the same argument."
        type: improvement
      - 
        text: "added `with_presence` flag for subscribe, default false."
        type: improvement
    date: ~
    version: v4.0.6
  - 
    changes: 
      - 
        text: "Required CGI."
        type: improvement
    version: v4.0.5
  - 
    changes: 
      - 
        text: Added
        type: feature
    version: v4.0.2
  - 
    changes: 
      - 
        text: "Updated dry-validation and EnvelopeSchema."
        type: improvement
    version: v4.0.1
  - 
    changes: 
      - 
        text: "Removed auth_key and uuid setters (#set_auth_key,"
        type: feature
      - 
        text: Added
        type: improvement
    version: v4.0.0
  - 
    changes: 
      - 
        text: "Restored auth_key and uuid setters. Important notice: they will be removed"
        type: improvement
    version: v3.8.3
  - 
    changes: 
      - 
        text: "Added :include_token parameter to history call."
        type: feature
    version: v3.8.2
  - 
    changes: 
      - 
        text: "Updated celluloid dependency."
        type: improvement
    version: v3.8.1
  - 
    changes: 
      - 
        text: "Release of celluloid version of pubnub gem. It's complete rewrite but public API doesn't change."
        type: improvement
    version: v3.8.0
features: 
  access:
    - ACCESS-GRANT
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-SYNC
    - PUBLISH-ASYNC
    - PUBLISH-MESSAGE-TTL
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
  notify:
    - REQUEST-MESSAGE-COUNT-EXCEEDED
name: ruby
schema: 1
scm: github.com/pubnub/ruby
version: "4.0.15"
