sudo: false

addons:
    code_climate:
        repo_token: 48739096f72763cbed9bd407efd2ed33151ce5663fb3181455128f06d6123ef3

before_install:
  - gem update bundler

language: ruby
rvm:
 - 2.3.0
 - 2.2.4
 - 2.1.7
 - 2.0.0
 - jruby

bundler_args: --without development

script: bundle exec rspec
